/*
 * Copyright © 2026 anyilanxin zxh(anyilanxin@aliyun.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
plugins {
    id 'kunpeng.build-publish'
}

description = "Kunpeng Engine Bpmn"

configure(jarInfo) {
    archiveName = "kunpeng-engine-process"
}

dependencies {
    implementation project(':kunpeng:utils')
    implementation project(':kunpeng:eventlog')
    implementation project(':kunpeng:cluster:cluster')
    implementation project(':kunpeng:cluster:cluster-raft')
    implementation project(':kunpeng:protocol:protocol-common')
    implementation project(':kunpeng:protocol:protocol-business')
    implementation project(':kunpeng:protocol:protocol-business-impl')
    implementation project(':kunpeng:broker:broker-client')
    implementation project(':kunpeng:engine:dmn-engine')
    implementation project(':kunpeng:scheduler')
    implementation project(':kunpeng:configuration')
    implementation project(':kunpeng:engine:script-engine')
    implementation project(':kunpeng:bpm-model:model-parse')
    implementation project(':kunpeng:repository:business-repository')
    implementation project(':kunpeng:repository:kvstore')
    implementation project(':kunpeng:structpack')

    implementation 'com.google.guava:guava'
    implementation 'org.agrona:agrona'
    implementation 'commons-codec:commons-codec'
    implementation 'io.micrometer:micrometer-core'
    implementation 'io.micrometer:micrometer-commons'
    implementation 'org.springframework:spring-beans'
    implementation 'org.apache.commons:commons-lang3'
    implementation "com.github.ben-manes.caffeine:caffeine"
    implementation 'com.fasterxml.jackson.core:jackson-annotations'

    testImplementation 'org.openjdk.jmh:jmh-core'
    testAnnotationProcessor platform(project(':bom:dependency-bom'))
    testAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess'
}
