# gradle---start
org.gradle.welcome=never
org.gradle.jvmargs=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Djib.httpTimeout=0 -Djib.console=plain
org.gradle.parallel=true
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.parallel=true
org.gradle.vfs.watch=true
org.gradle.caching=true
#ignore maven sha256 and sha512 check
systemProp.org.gradle.internal.publish.checksums.insecure=true
org.gradle.warning.mode=none
# gradle---end
# project--start
version=2026.8.0-alpha1
# spring-boot-dependencies
springBootVersion=4.1.0
anyiSnapshots=false
# grpc-bom
grpcBomVersion=1.83.1
# protobuf-bom
protobufBomVersion=4.36.0-RC2
# sbe-tool(uk.co.real-logic)
sbe_version=1.39.0
# project--end
