plugins {
    id 'kunpeng.build-publish'
}

description = "Jackson Datatype Document"

configure(jarInfo) {
    archiveName = "kunpeng-connector-jackson-datatype-document"
}


dependencies {
    implementation project(':connector:connector-sdk:core')
    implementation 'com.fasterxml.jackson.core:jackson-core'
    implementation 'com.fasterxml.jackson.core:jackson-annotations'
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.skyscreamer:jsonassert'
}
