/*
 * Copyright © 2026 anyilanxin zxh(anyilanxin@aliyun.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
plugins {
    id 'kunpeng.build-publish'
    id 'kunpeng.sbe-java'
}

description = "Kunpeng Sink Runtime"

configure(jarInfo) {
    archiveName = "kunpeng-sink"
}

dependencies {
    api project(':kunpeng:sink:sink-api')

    implementation project(':kunpeng:cluster:cluster')
    implementation project(':kunpeng:cluster:cluster-config')
    implementation project(':kunpeng:configuration')
    implementation project(':kunpeng:eventlog')
    implementation project(':kunpeng:protocol:protocol-common')
    implementation project(':kunpeng:protocol:protocol-business')
    implementation project(':kunpeng:protocol:protocol-business-impl')
    implementation project(':kunpeng:repository:business-repository')
    implementation project(':kunpeng:scheduler')
    implementation project(':kunpeng:structpack')
    implementation project(':kunpeng:utils')

    implementation 'tools.jackson.core:jackson-databind'
    implementation 'tools.jackson.core:jackson-core'
    implementation 'org.agrona:agrona'
    implementation 'io.micrometer:micrometer-core'
}
