/*
 * Copyright © 2026 anyilanxin zxh (anyilanxin@aliyun.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package io.atomix.raft.snapshot;

import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/** A store of locally persisted snapshots. */
public interface PersistedSnapshotStore {

  /** Returns the snapshot with the highest index, if any. */
  Optional<PersistedSnapshot> getLatestSnapshot();

  /**
   * Returns the snapshot with the highest index among the given type, if any. The default
   * implementation only matches the overall latest snapshot; stores should override it.
   */
  default Optional<PersistedSnapshot> getLatestSnapshot(final SnapshotType type) {
    return getLatestSnapshot().filter(snapshot -> snapshot.getType() == type);
  }

  /** Returns the snapshot at exactly the given index, if any. */
  Optional<PersistedSnapshot> getSnapshotAt(long index);

  /**
   * Returns the lower bound for log compaction: the log must not be compacted below the lowest
   * index covered by any retained snapshot.
   */
  CompletableFuture<Long> getCompactionBound();

  /** Returns the maximum number of snapshots retained by this store. */
  int getMaxSnapshotCount();

  /**
   * Deletes all snapshots at or after the given index.
   *
   * @return a future completed with the number of deleted snapshots
   */
  CompletableFuture<Integer> deleteSnapshotsFrom(long index);

  /** Removes all incomplete (pending or receiving) snapshots. */
  CompletableFuture<Void> abortPendingSnapshots();

  /**
   * 创建可本地填充后提交的临时快照，业务元数据（类型/版本/业务信息）随 manifest 持久化。
   *
   * @param index the Raft log index of the snapshot
   * @param term the Raft term of the snapshot
   * @param nodeId the id of the local node
   * @param replicationThreads number of threads available to replicate this snapshot
   * @param type the type of the snapshot, persisted in its manifest
   * @param version the business metadata version
   * @param businessInfo the business key-value manifest, generated by the business system
   * @return the transient snapshot, or empty if a snapshot at the same index and term exists
   */
  Optional<TransientSnapshot> newTransientSnapshot(
      long index,
      long term,
      String nodeId,
      int replicationThreads,
      SnapshotType type,
      int version,
      Map<String, String> businessInfo);

  /** Registers a listener notified when a new snapshot is persisted. */
  void addSnapshotListener(PersistedSnapshotListener listener);

  /** Removes a previously registered listener. */
  void removeSnapshotListener(PersistedSnapshotListener listener);

  /** 删除整个快照存储根目录并清空内存快照表，默认空实现。 */
  default CompletableFuture<Void> delete() {
    return CompletableFuture.completedFuture(null);
  }

  /** 关闭存储并清理资源，供关闭钩子调用，默认空实现。 */
  default void close() {}
}
