plugins {
    id 'kunpeng.build-publish'
}

description = "Connector HTTP Client"

configure(jarInfo) {
    archiveName = "kunpeng-connector-http-client"
}


dependencies {
    implementation 'org.slf4j:slf4j-api'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation 'com.google.http-client:google-http-client'
    implementation 'org.apache.httpcomponents.core5:httpcore5'
    implementation 'org.apache.httpcomponents.client5:httpclient5'
    implementation 'io.github.hakky54:ayza'
    implementation 'io.github.hakky54:ayza-for-pem'
    implementation 'org.apache.commons:commons-lang3'
    implementation project(':connector:connector-sdk:core')
    implementation 'com.github.ben-manes.caffeine:caffeine'

    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
    testImplementation 'org.wiremock:wiremock-standalone'
    testImplementation 'org.junit.jupiter:junit-jupiter-params'
    testImplementation 'uk.org.webcompere:system-stubs-core'
    testImplementation 'uk.org.webcompere:system-stubs-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.testcontainers:testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation project(':connector:connector-commons:connector-test-utils')
    testImplementation 'org.apache.commons:commons-text'
}
