#server.port=9898

# Local demo installation with simple authentication, not meant for production use
#camunda.client.grpc-address=http://127.0.0.1:26500

# You can use SaaS mode
#camunda.client.cloud.region=bru-2
#camunda.client.cloud.cluster-id=xxx
#camunda.client.auth.client-id=xxx
#camunda.client.auth.client-secret=xxx
