syntax = 'proto3';
package gateway_protocol;

option java_multiple_files = false;
option java_package = "com.anyilanxin.kunpeng.gateway.grpc.service";
option go_package = "./;pb";


message MessageCorrelationRequest {
  int64 processInstanceId = 2;
  string messageName = 4;
  string correlationKey = 5;
  string tenantId = 6;
  string variable = 7;
}


message MessageCorrelationResponse {
}



service MessageService {
  /*
   Iterates through all known partitions round-robin and activates up to the requested
   maximum and streams them back to the client as they are activated.

   Errors:
    INVALID_ARGUMENT:
     - type is blank (empty string, null)
     - worker is blank (empty string, null)
     - timeout less than 1
     - maxJobsToActivate is less than 1
  */
  rpc MessageCorrelation (MessageCorrelationRequest) returns (stream MessageCorrelationResponse) {
  }
}
