plugins {
    id 'kunpeng.build-publish'
}

description = "Connector Object Mapper Config"

configure(jarInfo) {
    archiveName = "kunpeng-connector-object-mapper"
}


dependencies {
    implementation 'tools.jackson.core:jackson-databind'
    implementation 'tools.jackson.core:jackson-core'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
}
