plugins {
    id 'kunpeng.build-publish'
}

description = "Connector FEEL evaluators"

configure(jarInfo) {
    archiveName = "kunpeng-connector-feel"
}


dependencies {
    implementation project(':connector:connector-sdk:core')
    implementation 'org.slf4j:slf4j-api'
    implementation project(':connector:connector-commons:connector-object-mapper')
    implementation 'com.alibaba:qlexpress4'
    implementation 'tools.jackson.core:jackson-databind'
    implementation 'tools.jackson.core:jackson-core'

    compileOnly project(':clients:client-java')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.skyscreamer:jsonassert'
}
